[build-dependencies.substrate-build-script-utils]
branch = 'master'
git = 'https://github.com/paritytech/substrate'
version = '3.0.0'

[dependencies]
sp-keyring = { version = "6.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
frame-system = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-transaction-payment = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", branch = "master" }
codec = { package = "parity-scale-codec", version = "3.1.2", features = ["derive"] }
async-trait = '0.1'
futures = '0.3'
jsonrpc-core = '18.0.0'
jsonrpc-pubsub = '18.0.0'
log = '0.4.8'
libsecp256k1 = { version = "0.7.0", default-features = false, features = ['static-context'] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
pallet-quantum-portal = { path = "../pallets/quamtum-portal"}
jsonrpsee = { version = "0.13.0", features = ["server", "macros"] }

[dependencies.clap]
features = ['derive']
version = '3.0'

[dependencies.fc-consensus]
version = '2.0.0-dev'
git = 'https://github.com/paritytech/frontier.git'
# git = 'https://github.com/ferrumnet/frontier.git'
# rev = '55029298e158ed4b046464c8951b4c5d79d6ea17'

[dependencies.fc-db]
version = "2.0.0-dev"
git = 'https://github.com/paritytech/frontier.git'
# git = 'https://github.com/ferrumnet/frontier.git'
# rev = '55029298e158ed4b046464c8951b4c5d79d6ea17'

[dependencies.fc-mapping-sync]
version = "2.0.0-dev"
git = 'https://github.com/paritytech/frontier.git'
# git = 'https://github.com/ferrumnet/frontier.git'
# rev = '55029298e158ed4b046464c8951b4c5d79d6ea17'

[dependencies.fc-rpc]
version = "2.0.0-dev"
git = 'https://github.com/paritytech/frontier.git'
# git = 'https://github.com/ferrumnet/frontier.git'
# rev = '55029298e158ed4b046464c8951b4c5d79d6ea17'

[dependencies.fc-rpc-core]
version = '1.1.0-dev'
git = 'https://github.com/paritytech/frontier.git'
# git = 'https://github.com/ferrumnet/frontier.git'
# rev = '55029298e158ed4b046464c8951b4c5d79d6ea17'

[dependencies.fp-consensus]
version = "2.0.0-dev"
git = 'https://github.com/paritytech/frontier.git'
# git = 'https://github.com/ferrumnet/frontier.git'
# rev = '55029298e158ed4b046464c8951b4c5d79d6ea17'

[dependencies.fp-rpc]
version = "3.0.0-dev"
git = 'https://github.com/paritytech/frontier.git'
# git = 'https://github.com/ferrumnet/frontier.git'
# rev = '55029298e158ed4b046464c8951b4c5d79d6ea17'

[dependencies.fp-storage]
version = "2.0.0"
git = 'https://github.com/paritytech/frontier.git'
# features = ["std"]
# git = 'https://github.com/ferrumnet/frontier.git'
# rev = '55029298e158ed4b046464c8951b4c5d79d6ea17'

[dependencies.frame-benchmarking]
branch = 'master'
git = 'https://github.com/paritytech/substrate'
version = '4.0.0-dev'

[dependencies.frame-benchmarking-cli]
branch = 'master'
git = 'https://github.com/paritytech/substrate'
version = '4.0.0-dev'

[dependencies.ferrum-x-runtime]
default-features = false
features = ['std']
path = '../runtime'

[dependencies.pallet-base-fee]
git = "https://github.com/paritytech/frontier/"
version = "1.0.0"
# git = 'https://github.com/ferrumnet/frontier.git'
# rev = '55029298e158ed4b046464c8951b4c5d79d6ea17'

[dependencies.pallet-dynamic-fee]
version = "4.0.0-dev"
git = 'https://github.com/paritytech/frontier.git'
# git = 'https://github.com/ferrumnet/frontier.git'
# rev = '55029298e158ed4b046464c8951b4c5d79d6ea17'

[dependencies.pallet-ethereum]
version = '4.0.0-dev'
git = 'https://github.com/paritytech/frontier.git'
# git = 'https://github.com/ferrumnet/frontier.git'
# rev = '55029298e158ed4b046464c8951b4c5d79d6ea17'

[dependencies.pallet-evm]
version = "6.0.0-dev"
git = 'https://github.com/paritytech/frontier.git'
# git = 'https://github.com/ferrumnet/frontier.git'
# rev = '55029298e158ed4b046464c8951b4c5d79d6ea17'

[dependencies.pallet-transaction-payment-rpc]
branch = 'master'
git = 'https://github.com/paritytech/substrate'
version = '4.0.0-dev'

[dependencies.sc-basic-authorship]
branch = 'master'
git = 'https://github.com/paritytech/substrate'
version = '0.10.0-dev'

[dependencies.sc-cli]
branch = 'master'
features = ['wasmtime']
git = 'https://github.com/paritytech/substrate'
version = '0.10.0-dev'

[dependencies.sc-client-api]
branch = 'master'
git = 'https://github.com/paritytech/substrate'
version = '4.0.0-dev'

[dependencies.sc-consensus]
branch = 'master'
git = 'https://github.com/paritytech/substrate'
version = '0.10.0-dev'

[dependencies.sc-consensus-aura]
branch = 'master'
git = 'https://github.com/paritytech/substrate'
version = '0.10.0-dev'

[dependencies.sc-consensus-manual-seal]
branch = 'master'
git = 'https://github.com/paritytech/substrate'
version = '0.10.0-dev'

[dependencies.sc-executor]
branch = 'master'
features = ['wasmtime']
git = 'https://github.com/paritytech/substrate'
version = '0.10.0-dev'

[dependencies.sc-finality-grandpa]
branch = 'master'
git = 'https://github.com/paritytech/substrate'
version = '0.10.0-dev'

[dependencies.sc-keystore]
branch = 'master'
git = 'https://github.com/paritytech/substrate'
version = '4.0.0-dev'

[dependencies.sc-network]
branch = 'master'
git = 'https://github.com/paritytech/substrate'
version = '0.10.0-dev'

[dependencies.sc-rpc]
branch = 'master'
git = 'https://github.com/paritytech/substrate'
version = '4.0.0-dev'

[dependencies.sc-rpc-api]
branch = 'master'
git = 'https://github.com/paritytech/substrate'
version = '0.10.0-dev'

[dependencies.sc-service]
branch = 'master'
features = ['wasmtime']
git = 'https://github.com/paritytech/substrate'
version = '0.10.0-dev'

[dependencies.sc-telemetry]
branch = 'master'
git = 'https://github.com/paritytech/substrate'
version = '4.0.0-dev'

[dependencies.sc-transaction-pool]
branch = 'master'
git = 'https://github.com/paritytech/substrate'
version = '4.0.0-dev'

[dependencies.sc-transaction-pool-api]
branch = 'master'
git = 'https://github.com/paritytech/substrate'
version = '4.0.0-dev'

[dependencies.sp-api]
branch = 'master'
git = 'https://github.com/paritytech/substrate'
version = '4.0.0-dev'

[dependencies.sp-block-builder]
branch = 'master'
git = 'https://github.com/paritytech/substrate'
version = '4.0.0-dev'

[dependencies.sp-blockchain]
branch = 'master'
git = 'https://github.com/paritytech/substrate'
version = '4.0.0-dev'

[dependencies.sp-consensus]
branch = 'master'
git = 'https://github.com/paritytech/substrate'
version = '0.10.0-dev'

[dependencies.sp-consensus-aura]
branch = 'master'
git = 'https://github.com/paritytech/substrate'
version = '0.10.0-dev'

[dependencies.sp-core]
branch = 'master'
git = 'https://github.com/paritytech/substrate'
version = '6.0.0'
# features = ['scale-info']

[dependencies.sp-finality-grandpa]
branch = 'master'
git = 'https://github.com/paritytech/substrate'
version = '4.0.0-dev'

[dependencies.sp-inherents]
branch = 'master'
git = 'https://github.com/paritytech/substrate'
version = '4.0.0-dev'

[dependencies.sp-runtime]
branch = 'master'
git = 'https://github.com/paritytech/substrate'
version = '6.0.0'

[dependencies.sp-timestamp]
branch = 'master'
git = 'https://github.com/paritytech/substrate'
version = '4.0.0-dev'

[dependencies.fp-evm]
git = 'https://github.com/paritytech/frontier'
version = '3.0.0-dev'

[dependencies.sp-keystore]
branch = 'master'
git = 'https://github.com/paritytech/substrate'

[dependencies.substrate-frame-rpc-system]
branch = 'master'
git = 'https://github.com/paritytech/substrate'
version = '4.0.0-dev'

[package]
authors = ['Ferrum Network <https://github.com/ferrumnet>']
build = 'build.rs'
description = 'Ferrum Network Poc Testnet'
edition = '2021'
homepage = 'https://ferrum.network'
license = 'Unlicense'
name = 'ferrum-x-network'
publish = false
repository = 'https://github.com/ferrumnet/ferrum-x-network/'
version = '0.0.1'
[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[features]
aura = ['ferrum-x-runtime/aura']
default = ['aura']
manual-seal = ['ferrum-x-runtime/manual-seal']
rpc_binary_search_estimate = ['fc-rpc/rpc_binary_search_estimate']
runtime-benchmarks = ['ferrum-x-runtime/runtime-benchmarks']
