[settings]
timeout = 1000

[relaychain]
default_command = "~/Documents/ferrum/polkadot-sdk/target/release/polkadot"
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"

  [[relaychain.nodes]]
  name = "bob"

  [[relaychain.nodes]]
  name = "charlie"

[[parachains]]
id = 1000
chain = "dev"
force_decorator = "generic-evm"
cumulus_based = true
add_to_genesis = true
register_para = true
default_args = [ "-lruntime=trace", "--rpc-external" ]

  [parachains.collator]
  name = "collator01"
  command = "~/Documents/ferrum/ferrum-network/target/release/ferrum-network"
  args = ["-lruntime=trace", "--rpc-external"]