name: Rust

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    name: 'Run Rust tests'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Rust Setup
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly-2022-10-10
        target: wasm32-unknown-unknown
        override: true
    - name: Install protoc
      uses: arduino/setup-protoc@v1
    - name: Run tests
      run: cargo test --locked --verbose --all
    - name: Ensure runtime-benchmarks and try-runtime features compiles
      run: cargo check --release --features=runtime-benchmarks,try-runtime

  lint:
    name: 'Run lints'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Rust Setup
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly-2022-10-10
        target: wasm32-unknown-unknown
        override: true
        components: rustfmt, clippy
    - name: Install protoc
      uses: arduino/setup-protoc@v1
    - name: Check Cargo.toml Format
      run: |
        if taplo --version &> /dev/null; then
          echo "taplo-cli is already installed"
        else
          cargo install taplo-cli
        fi
        taplo fmt --check
    - name: Rustfmt
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy --all --features runtime-benchmarks,try-runtime -- -D warnings